import {
  app,
  BrowserWindow,
  globalShortcut,
  ipcMain,
  Menu,
  session,
  Tray,
} from "electron";
import { openMainWindow } from "./services/windows";
import Items from "../models/Items";
import TooltipWindow from "../models/TooltipWindow";
import OCRProcess from "../models/OCRProcess";
import AlwaysOnTopProcess from "../models/AlwaysOnTopProcess";
import path from "path";
import IpcConstants from "../models/IpcConstants";

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;
let items: Items;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require("electron-squirrel-startup")) {
  app.quit();
}

// Better performance when a menu is not needed
// Menu.setApplicationMenu(null);

app.on("ready", async () => {
  session.defaultSession.webRequest.onHeadersReceived((details, callback) => {
    callback({
      responseHeaders: {
        ...details.responseHeaders,
        "Content-Security-Policy": [
          "default-src * 'unsafe-inline' 'unsafe-eval' data: blob:; script-src * 'unsafe-inline' 'unsafe-eval' data: blob:; connect-src *; img-src * data: blob:; style-src * 'unsafe-inline'; font-src * data:; media-src *; object-src *;",
        ],
      },
    });
  });

  openMainWindow(MAIN_WINDOW_WEBPACK_ENTRY, MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY);
  items = new Items();
  await items.fetchItems();

  setInterval(
    () => {
      console.log("Refetching updated data");
      items.fetchItems();
    },
    1000 * 60 * 5
  );

  items.initializeSearchIndex();

  // console.log(items);
  const ocr = new OCRProcess(items, BrowserWindow.getAllWindows()[0]);
  ocr.initialize();

  const tray = new Tray(path.join(app.getAppPath(), "/favicon.ico"));

  const contextMenu = Menu.buildFromTemplate([
    {
      role: "about",
      label: "Tarkov Price Checker",
      icon: path.join(app.getAppPath(), "/favicon-16x16.png"),
      enabled: false,
    },
    {
      type: "separator",
    },
    {
      role: "quit",
      label: "Quit App",
    },
  ]);

  tray.setToolTip("Tarkov Price Checker");
  tray.setContextMenu(contextMenu);

  globalShortcut.register("F2", () => {
    BrowserWindow.getAllWindows()[0].webContents.send(IpcConstants.DeleteItem);
  });

  globalShortcut.register("F3", () => {
    console.log("Adding quantity to most recently added item");
    BrowserWindow.getAllWindows()[0].webContents.send(
      IpcConstants.AddToItemCount
    );
  });

  globalShortcut.register("F12", () => {
    BrowserWindow.getAllWindows()[0].webContents.openDevTools();
  });

  ipcMain.on(IpcConstants.EnableTooltips, async (event, ...args) => {
    console.log("ON ENABLE TOOLTIPS");
    const tooltipWindow = new TooltipWindow();
    tooltipWindow.on("ready-to-show", () => {
      console.log("Tooltip window is ready to show");
      setTimeout(() => {
        const alwaysOnTopProcess = new AlwaysOnTopProcess();
        alwaysOnTopProcess.initialize();
        ocr.tooltipWindow = tooltipWindow;
        BrowserWindow.getAllWindows()[0].webContents.send(
          IpcConstants.TooltipsReady
        );
      }, 1000);
    });
  });
});

app.on("window-all-closed", () => {
  if (process.platform !== "darwin") {
    app.quit();
  }
});

// MAC
app.on("activate", () => {
  if (BrowserWindow.getAllWindows().length === 0) {
    // openMainWindow(MAIN_WINDOW_WEBPACK_ENTRY, MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY);
  }
});
