import {
  app,
  BrowserWindow,
  globalShortcut,
  ipcMain,
  Menu,
  session,
  Tray,
} from "electron";
import { openMainWindow } from "./services/windows";
import Items from "../models/Items";
import TooltipWindow from "../models/TooltipWindow";
import OCRProcess from "../models/OCRProcess";
import AlwaysOnTopProcess from "../models/AlwaysOnTopProcess";
import path from "path";
import IpcConstants from "../models/IpcConstants";
import log from "electron-log/main";
import { isDev } from "../utils";

declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

try {
  // This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
  // plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
  // whether you're running in development or production).
  let items: Items;

  log.initialize();

  // Handle creating/removing shortcuts on Windows when installing/uninstalling.
  if (require("electron-squirrel-startup")) {
    app.quit();
  }

  // Better performance when a menu is not needed
  // Menu.setApplicationMenu(null);

  app.on("ready", async () => {
    session.defaultSession.webRequest.onHeadersReceived((details, callback) => {
      callback({
        responseHeaders: {
          ...details.responseHeaders,
          "Content-Security-Policy": [
            "default-src * 'unsafe-inline' 'unsafe-eval' data: blob:; script-src * 'unsafe-inline' 'unsafe-eval' data: blob:; connect-src *; img-src * data: blob:; style-src * 'unsafe-inline'; font-src * data:; media-src *; object-src *;",
          ],
        },
      });
    });

    log.info(
      "OPENING MAIN WINDOW",
      MAIN_WINDOW_WEBPACK_ENTRY,
      MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY
    );
    const mainWindow = openMainWindow(
      MAIN_WINDOW_WEBPACK_ENTRY,
      MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY
    );
    (await mainWindow).setIgnoreMouseEvents(true);
    (await mainWindow).on("close", () => {
      app.quit();
    });
    items = new Items();
    await items.fetchItems();

    setInterval(() => {
      console.log("Refetching updated data");
      items.fetchItems();
    }, 1000 * 60 * 15);

    items.initializeSearchIndex();

    const ocr = new OCRProcess(items, BrowserWindow.getAllWindows()[0]);
    ocr.initialize();
    console.log("OCR PROCESS INITIALIZED");
    const tooltipWindow = new TooltipWindow();
    tooltipWindow.setIgnoreMouseEvents(true);
    console.log("TOOLTIP WINDOW CREATED");
    tooltipWindow.on("ready-to-show", () => {
      console.log("TOOLTIP WINDOW READY TO SHOW");
      setTimeout(() => {
        const alwaysOnTopProcess = new AlwaysOnTopProcess();
        alwaysOnTopProcess.initialize();
        ocr.tooltipWindow = tooltipWindow;
        BrowserWindow.getAllWindows()[0].webContents.send(
          IpcConstants.TooltipsReady
        );
      }, 1000);
    });

    // FOR SOME REASON THESE BREAK THE APP WHEN PACKAGED |||||||||||||||||||||||||||||| WARNING
    // const tray = new Tray(path.join(app.getAppPath(), "/favicon.ico"));

    // const contextMenu = Menu.buildFromTemplate([
    //   {
    //     role: "about",
    //     label: "Tarkov Price Checker",
    //     icon: path.join(app.getAppPath(), "/favicon-16x16.png"),
    //     enabled: false,
    //   },
    //   {
    //     type: "separator",
    //   },
    //   {
    //     role: "quit",
    //     label: "Quit App",
    //   },
    // ]);

    // tray.setToolTip("Tarkov Price Checker");
    // tray.setContextMenu(contextMenu);

    globalShortcut.register("F1", () => {
      console.log("Toggling main window visibility");
      console.log(BrowserWindow.getAllWindows()[0].isVisible());
      if (BrowserWindow.getAllWindows()[0].isVisible()) {
        BrowserWindow.getAllWindows()[0].hide();
      } else {
        BrowserWindow.getAllWindows()[0].show();
      }
    });

    globalShortcut.register("F2", () => {
      BrowserWindow.getAllWindows()[0].webContents.send(
        IpcConstants.DeleteItem
      );
    });

    globalShortcut.register("F3", () => {
      BrowserWindow.getAllWindows()[0].webContents.send(
        IpcConstants.DeleteLastItem
      );
    });

    globalShortcut.register("F4", () => {
      BrowserWindow.getAllWindows()[0].webContents.send(
        IpcConstants.AddToItemCount
      );
    });

    globalShortcut.register("F12", () => {
      BrowserWindow.getAllWindows()[0].webContents.openDevTools();
    });

    // log.info("MEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEOW");
    // ipcMain.on(IpcConstants.EnableTooltips, async (event, ...args) => {
    //   const tooltipWindow = new TooltipWindow();
    //   tooltipWindow.on("ready-to-show", () => {
    //     setTimeout(() => {
    //       const alwaysOnTopProcess = new AlwaysOnTopProcess();
    //       alwaysOnTopProcess.initialize();
    //       ocr.tooltipWindow = tooltipWindow;
    //       BrowserWindow.getAllWindows()[0].webContents.send(
    //         IpcConstants.TooltipsReady
    //       );
    //     }, 1000);
    //   });
    // });
  });

  app.on("window-all-closed", () => {
    if (process.platform !== "darwin") {
      app.quit();
    }
  });

  // MAC
  app.on("activate", () => {
    if (BrowserWindow.getAllWindows().length === 0) {
      // openMainWindow(MAIN_WINDOW_WEBPACK_ENTRY, MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY);
    }
  });
} catch (e) {
  log.error("Error in main process:", e);
}
