import {
  app,
  BrowserWindow,
  globalShortcut,
  ipcMain,
  Menu,
  session,
  Tray,
} from "electron";
import { openMainWindow } from "./services/windows";
import Items from "../models/Items";
import TooltipWindow from "../models/TooltipWindow";
import OCRProcess from "../models/OCRProcess";
import AlwaysOnTopProcess from "../models/AlwaysOnTopProcess";
import path from "path";
import IpcConstants from "../models/IpcConstants";
import log from "electron-log/main";
import { isDev } from "../utils";
import { ChildProcessWithoutNullStreams, spawn } from "child_process";
import fs from "fs";

declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

try {
  // This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
  // plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
  // whether you're running in development or production).
  let items: Items;
  let screenConfigureStep: 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 = 0;
  let screenConfigureProcess: ChildProcessWithoutNullStreams | null = null;

  log.initialize();

  // Handle creating/removing shortcuts on Windows when installing/uninstalling.
  if (require("electron-squirrel-startup")) {
    app.quit();
  }

  // Better performance when a menu is not needed
  // Menu.setApplicationMenu(null);

  app.on("ready", async () => {
    session.defaultSession.webRequest.onHeadersReceived((details, callback) => {
      callback({
        responseHeaders: {
          ...details.responseHeaders,
          "Content-Security-Policy": [
            "default-src * 'unsafe-inline' 'unsafe-eval' data: blob:; script-src * 'unsafe-inline' 'unsafe-eval' data: blob:; connect-src *; img-src * data: blob:; style-src * 'unsafe-inline'; font-src * data:; media-src *; object-src *;",
          ],
        },
      });
    });

    log.info(
      "OPENING MAIN WINDOW",
      MAIN_WINDOW_WEBPACK_ENTRY,
      MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY
    );
    const mainWindow = openMainWindow(
      MAIN_WINDOW_WEBPACK_ENTRY,
      MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY
    );
    (await mainWindow).setIgnoreMouseEvents(true);
    (await mainWindow).on("close", () => {
      app.quit();
    });

    const tooltipWindow = new TooltipWindow();
    tooltipWindow.setIgnoreMouseEvents(true);
    console.log("TOOLTIP WINDOW CREATED");

    items = new Items();
    items
      .fetchItems()
      .then(async () => {
        setInterval(() => {
          console.log("Refetching updated data");
          items.fetchItems();
        }, 1000 * 60 * 15);

        do {
          try {
            items.initializeSearchIndex();
            console.log("Item search index initialized");
            break;
          } catch (error) {
            console.log("Error initializing search index, retrying...", error);
            await new Promise((resolve) => setTimeout(resolve, 500));
          }
        } while (items.items.length === 0);

        const ocr = new OCRProcess(items, BrowserWindow.getAllWindows()[0]);
        ocr.initialize();
        console.log("OCR PROCESS INITIALIZED");
        ocr.tooltipWindow = tooltipWindow;
        BrowserWindow.getAllWindows()[0].webContents.send(
          IpcConstants.ItemsDatabaseReady
        );
      })
      .catch((error) => {
        console.log("FAILED TO FETCH ITEMS FROM API:", error);
        BrowserWindow.getAllWindows()[0].webContents.send(
          IpcConstants.ItemsDatabaseFailed
        );
      });

    tooltipWindow.on("ready-to-show", () => {
      console.log("TOOLTIP WINDOW READY TO SHOW");
      setTimeout(() => {
        const alwaysOnTopProcess = new AlwaysOnTopProcess();
        alwaysOnTopProcess.initialize();
        BrowserWindow.getAllWindows()[0].webContents.send(
          IpcConstants.TooltipsReady
        );
      }, 1000);
    });

    // FOR SOME REASON THESE BREAK THE APP WHEN PACKAGED |||||||||||||||||||||||||||||| WARNING
    // const tray = new Tray(path.join(app.getAppPath(), "/favicon.ico"));

    // const contextMenu = Menu.buildFromTemplate([
    //   {
    //     role: "about",
    //     label: "Tarkov Price Checker",
    //     icon: path.join(app.getAppPath(), "/favicon-16x16.png"),
    //     enabled: false,
    //   },
    //   {
    //     type: "separator",
    //   },
    //   {
    //     role: "quit",
    //     label: "Quit App",
    //   },
    // ]);

    // tray.setToolTip("Tarkov Price Checker");
    // tray.setContextMenu(contextMenu);

    globalShortcut.register("F1", () => {
      console.log("Toggling main window visibility");
      console.log(BrowserWindow.getAllWindows()[0].isVisible());
      if (BrowserWindow.getAllWindows()[0].isVisible()) {
        BrowserWindow.getAllWindows()[0].hide();
      } else {
        BrowserWindow.getAllWindows()[0].show();
      }
    });

    globalShortcut.register("F2", () => {
      BrowserWindow.getAllWindows()[0].webContents.send(
        IpcConstants.DeleteItem
      );
    });

    globalShortcut.register("F3", () => {
      BrowserWindow.getAllWindows()[0].webContents.send(
        IpcConstants.DeleteLastItem
      );
    });

    globalShortcut.register("F4", () => {
      BrowserWindow.getAllWindows()[0].webContents.send(
        IpcConstants.AddToItemCount
      );
    });

    globalShortcut.register("F6", () => {
      console.log("On step ", screenConfigureStep);
      if (!BrowserWindow.getAllWindows()[0].isVisible()) {
        BrowserWindow.getAllWindows()[0].show();
      }

      if (screenConfigureStep === 0) {
        const startTime = Date.now();
        console.log("Starting screen configure");
        BrowserWindow.getAllWindows()[0].webContents.send(
          IpcConstants.StartScreenConfigure
        );
        BrowserWindow.getAllWindows()[0].webContents.send(
          IpcConstants.DisableScreenConfigureNeeded
        );
        screenConfigureStep = 1;
        screenConfigureProcess = isDev()
          ? spawn(
              path.join(app.getAppPath(), "/lib/ocr/configure_screen.exe")
              // {
              //   detached: true,
              //   shell: true,
              // }
            )
          : spawn(
              path.join(process.resourcesPath, "/ocr/configure_screen.exe")
            );

        screenConfigureProcess.stdout.setEncoding("utf-8");
        screenConfigureProcess.stdout.on("data", function (data) {
          console.log("Screen configure stderr data:", data.toString());
          isDev()
            ? console.log("stderr: " + data)
            : log.error("stderr: " + data);

          if (
            data.toString().includes("Searching") &&
            screenConfigureStep === 3
          ) {
            screenConfigureStep = 4;
            BrowserWindow.getAllWindows()[0].webContents.send(
              IpcConstants.ScreenConfigureScanningSingleRow
            );
          }

          if (
            data.toString().includes("RESULT||") &&
            screenConfigureStep === 4
          ) {
            screenConfigureStep = 5;
            BrowserWindow.getAllWindows()[0].webContents.send(
              IpcConstants.ScreenConfigureScanComplete
            );

            const configData = data
              .toString()
              .replace("RESULT||", "")
              .split("||");
            const offsetX = configData[0];
            const offsetY = configData[1];
            const formattedConfigData = {
              offsetX: parseInt(offsetX),
              offsetY: parseInt(offsetY),
            };

            fs.writeFileSync(
              isDev()
                ? path.join(app.getAppPath(), "/lib/ocr/scanningConfig.json")
                : path.join(process.resourcesPath, "/ocr/scanningConfig.json"),
              JSON.stringify(formattedConfigData)
            );
          }
        });

        screenConfigureProcess.on("close", function (code) {
          console.log("Screen configure process closed with code:", code);
          if (screenConfigureStep !== 5) {
            BrowserWindow.getAllWindows()[0].webContents.send(
              IpcConstants.EndScreenConfigure
            );
          }
          screenConfigureStep = 0;
          screenConfigureProcess = null;
        });

        if (typeof screenConfigureProcess.pid !== "number") {
          console.error("Error: Failed to spawn subprocess. PID is undefined.");
          BrowserWindow.getAllWindows()[0].webContents.send(
            IpcConstants.ScreenConfigureFailed
          );
          // Throw an error or handle the failure
        } else {
          console.log(
            `Spawned subprocess correctly with PID: ${screenConfigureProcess.pid}`
          );

          const timeToWait = 1000 - (Date.now() - startTime);

          setTimeout(
            () => {
              console.log("Screen configure step 1 complete");
              screenConfigureStep = 2;
              BrowserWindow.getAllWindows()[0].webContents.send(
                IpcConstants.ScreenConfigureStarted
              );
            },
            timeToWait > 0 ? timeToWait : 0
          );
        }
      }

      if (screenConfigureStep === 2 && screenConfigureProcess) {
        console.log("Advancing to step 3, searching for single row dimensions");
        screenConfigureStep = 3;
        screenConfigureProcess.stdin.write("NEXT\n");
      }
    });

    globalShortcut.register("F12", () => {
      BrowserWindow.getAllWindows()[0].webContents.openDevTools();
    });

    // log.info("MEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEOW");
    // ipcMain.on(IpcConstants.EnableTooltips, async (event, ...args) => {
    //   const tooltipWindow = new TooltipWindow();
    //   tooltipWindow.on("ready-to-show", () => {
    //     setTimeout(() => {
    //       const alwaysOnTopProcess = new AlwaysOnTopProcess();
    //       alwaysOnTopProcess.initialize();
    //       ocr.tooltipWindow = tooltipWindow;
    //       BrowserWindow.getAllWindows()[0].webContents.send(
    //         IpcConstants.TooltipsReady
    //       );
    //     }, 1000);
    //   });
    // });
  });

  app.on("window-all-closed", () => {
    if (process.platform !== "darwin") {
      app.quit();
    }
  });

  // MAC
  app.on("activate", () => {
    if (BrowserWindow.getAllWindows().length === 0) {
      // openMainWindow(MAIN_WINDOW_WEBPACK_ENTRY, MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY);
    }
  });
} catch (e) {
  log.error("Error in main process:", e);
}
